#makefile for 2degas

EXE=rept.x

FC=mpiifort
FFLAGS=-g -O2 -fpp -I

SRC=main.f reptation.f

INCS=ewald.h 
OBJ=main.o reptation.o

$(EXE):$(OBJ)
	$(FC) $(LDFLAGS) -o $@ $(OBJ)

$(OBJ):$(SRC)
	$(FC) $(FFLAGS) -I$(INCS) -c $(SRC) 

setup: setup.o
	$(FC) -o setup.x setup.f reptation.f

clean:
	-rm $(OBJ) $(EXE)
