# makefile


# Add inputs and outputs from these tool invocations to the build variables 

#F77 parallel version
F77_EXE=rept-scal.x
F77=scorep mpif77
F77_SRC = main.f reptation.f
INCS=ewald.h
FFLAGS=-fpp -O2 -g
F77_OBJS = main.o reptation.o

all : $(F77_EXE) 
 

#
#  F77
#
$(F77_EXE):$(F77_OBJS)
	$(F77) $(LDFLAGS) -o $@ $(F77_OBJS)

%.o:%.f
	$(F77) $(FFLAGS) -c -I$(INCS) $<

#
#

clean:
	-rm $(F77_EXE) *.o


